apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: goat
  janus-idp.io/tekton: goat
  backstage.io/kubernetes-id: goat
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: goat
resources:
- deployment.yaml
- route.yaml
- service.yaml
