apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: goat
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: goat 
  name: goat
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: goat 
